### ISSUE TITLE
Form not present in 3.0

### ISSUE THREAD

**Issue by ndarilek** [henrikerola/scaladin#12]
I'm attempting to build and install 3.0 locally so I can port my new project to Vaadin 7. One big piece which I'm missing, though, is the Form class.

I tried porting from 2.x to 3, but the architecture has changed somewhat, and it wasn't a straight port. I'm also not familiar enough with Scaladin internals, but since the class is only 47 lines, I imagine the port wouldn't be tough for someone who does understand the various mixins and traits.

Would it be possible to port the old Form class to 3.0?

Thanks.

**Comment by mheinola** [comment]
Hi,

Form is deprecated in Vaadin 7, could you use the FieldGroup of Scaladin (although I'm not sure if it's fully ready yet either?)

Form in Vaadin: @deprecated As of 7.0, use {@link FieldGroup} instead of {@link Form} for more flexibility.

FieldGroup: https://github.com/henrikerola/scaladin/blob/3.0/addon/src/main/scala/vaadin/scala/FieldGroup.scala 

Example usage: https://github.com/mheinola/scaladin/blob/3.0-addressbook-demo/demo/src/main/scala/vaadin/scala/demo/DemoUI.scala#L108

br,
- Matti

**Comment by ndarilek** [comment]
OK, that's fair. Marking as closed.
